### ISSUE TITLE
Sometimes the test harness crashes instead of handling the rate limit as it seems

### ISSUE THREAD

**Issue by tyll** [linux-system-roles/test-harness#55]
Test harness crashes instead of handling error:
@yontalcar maybe we should add better logging and retry more just in case; errors are here:

```
Jun 14 07:29:41  systemd[1]: Started Linux System Roles Test Harness 8.
Jun 14 07:29:54  docker[24745]: Traceback (most recent call last):
Jun 14 07:29:54  docker[24745]:   File "/test/run-tests", line 841, in <module>
Jun 14 07:29:54  docker[24745]:     sys.exit(main())
Jun 14 07:29:54  docker[24745]:   File "/test/run-tests", line 826, in main
Jun 14 07:29:54  docker[24745]:     task = choose_task(gh, repos, images, config)
Jun 14 07:29:54  docker[24745]:   File "/test/run-tests", line 492, in choose_task
Jun 14 07:29:54  docker[24745]:     commands = get_comment_commands(gh, owner, repo, number)
Jun 14 07:29:54  docker[24745]:   File "/test/run-tests", line 460, in get_comment_commands
Jun 14 07:29:54  docker[24745]:     comments = get_comments(gh, owner, repo, pullnr)
Jun 14 07:29:54  docker[24745]:   File "/test/run-tests", line 438, in get_comments
Jun 14 07:29:54  docker[24745]:     result = gh.get(f"repos/{owner}/{repo}/issues/{pullnr}/comments")
Jun 14 07:29:54  docker[24745]:   File "/test/run-tests", line 133, in get
Jun 14 07:29:54  docker[24745]:     r.raise_for_status()
Jun 14 07:29:54  docker[24745]:   File "/usr/lib/python3.6/site-packages/requests/models.py", line 940, in raise_for_status
Jun 14 07:29:54  docker[24745]:     raise HTTPError(http_error_msg, response=self)
Jun 14 07:29:54  docker[24745]: requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://api.github.com/repos/linux-system-roles/storage/issues/26/comments
Jun 14 07:29:55  systemd[1]: lsr-test-harness@8.service: Main process exited, code=exited, status=1/FAILURE
Jun 14 07:29:55  systemd[1]: lsr-test-harness@8.service: Failed with result 'exit-code'.
Jun 14 07:30:55  systemd[1]: lsr-test-harness@8.service: Service RestartSec=1min expired, scheduling restart.
Jun 14 07:30:55  systemd[1]: lsr-test-harness@8.service: Scheduled restart job, restart counter is at 12.
Jun 14 07:30:55  systemd[1]: Stopped Linux System Roles Test Harness 8.
Jun 14 07:30:55  systemd[1]: Starting Linux System Roles Test Harness 8...
Jun 14 07:30:55  docker[26904]: Error response from daemon: No such container: lsr-test-harness-8
Jun 14 07:30:55  docker[26946]: Trying to pull repository docker.io/linuxsystemroles/test-harness ...
Jun 14 07:31:01  docker[26946]: sha256:18492c58fdc9c18697bb0b6bd804c23eb2029d47649f7150d0c252922cbfac90: Pulling from docker.io/linuxsystemroles/test-harness
Jun 14 07:31:01  docker[26946]: Digest: sha256:18492c58fdc9c18697bb0b6bd804c23eb2029d47649f7150d0c252922cbfac90
Jun 14 07:31:01  docker[26946]: Status: Image is up to date for docker.io/linuxsystemroles/test-harness:latest
Jun 14 07:31:01  systemd[1]: Started Linux System Roles Test Harness 8.
Jun 14 07:31:14  docker[27368]: >>> Rate limiting hit, waiting for 3600 seconds...
Jun 14 08:05:47  systemd[1]: Stopping Linux System Roles Test Harness 8...
Jun 14 08:05:47  docker[37664]: lsr-test-harness-8
Jun 14 08:05:47  systemd[1]: lsr-test-harness@8.service: Main process exited, code=exited, status=137/n/a
Jun 14 08:05:47  systemd[1]: lsr-test-harness@8.service: Failed with result 'exit-code'.
Jun 14 08:05:47  systemd[1]: Stopped Linux System Roles Test Harness 8.
Jun 14 08:09:46  systemd[1]: Starting Linux System Roles Test Harness 8...
Jun 14 08:09:46  docker[39364]: Error response from daemon: No such container: lsr-test-harness-8
Jun 14 08:09:46  docker[39374]: Trying to pull repository docker.io/linuxsystemroles/test-harness ...
Jun 14 08:09:48  docker[39374]: sha256:18492c58fdc9c18697bb0b6bd804c23eb2029d47649f7150d0c252922cbfac90: Pulling from docker.io/linuxsystemroles/test-harness
Jun 14 08:09:48  docker[39374]: Digest: sha256:18492c58fdc9c18697bb0b6bd804c23eb2029d47649f7150d0c252922cbfac90
Jun 14 08:09:48  docker[39374]: Status: Image is up to date for docker.io/linuxsystemroles/test-harness:latest
Jun 14 08:09:48  systemd[1]: Started Linux System Roles Test Harness 8.
Jun 14 08:10:04  docker[39386]: >>> bkr-harness-8: linux-system-roles/network: pull #119 (225ba70) on rhel-8
Jun 14 08:10:17  docker[39386]: Traceback (most recent call last):
Jun 14 08:10:17  docker[39386]:   File "/test/run-tests", line 614, in handle_task
Jun 14 08:10:17  docker[39386]:     statuses = get_statuses(gh, task.owner, task.repo, task.head)
Jun 14 08:10:17  docker[39386]:   File "/test/run-tests", line 427, in get_statuses
Jun 14 08:10:17  docker[39386]:     for status in gh.get(f"repos/{owner}/{repo}/statuses/{sha}").json():
Jun 14 08:10:17  docker[39386]:   File "/test/run-tests", line 133, in get
Jun 14 08:10:17  docker[39386]:     r.raise_for_status()
Jun 14 08:10:17  docker[39386]:   File "/usr/lib/python3.6/site-packages/requests/models.py", line 940, in raise_for_status
Jun 14 08:10:17  docker[39386]:     raise HTTPError(http_error_msg, response=self)
Jun 14 08:10:17  docker[39386]: requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://api.github.com/repos/linux-system-roles/network/statuses/225ba70a43473de3fd874bc62982cabb28cbfe35
Jun 14 08:10:17  docker[39386]: During handling of the above exception, another exception occurred:
Jun 14 08:10:17  docker[39386]: Traceback (most recent call last):
Jun 14 08:10:17  docker[39386]:   File "/test/run-tests", line 841, in <module>
Jun 14 08:10:17  docker[39386]:     sys.exit(main())
Jun 14 08:10:17  docker[39386]:   File "/test/run-tests", line 834, in main
Jun 14 08:10:17  docker[39386]:     handle_task(gh, args, config, task, args.dry_run)
Jun 14 08:10:17  docker[39386]:   File "/test/run-tests", line 701, in handle_task
Jun 14 08:10:17  docker[39386]:     else "",
Jun 14 08:10:17  docker[39386]:   File "/test/run-tests", line 125, in post
Jun 14 08:10:17  docker[39386]:     r.raise_for_status()
Jun 14 08:10:17  docker[39386]:   File "/usr/lib/python3.6/site-packages/requests/models.py", line 940, in raise_for_status
Jun 14 08:10:17  docker[39386]:     raise HTTPError(http_error_msg, response=self)
Jun 14 08:10:17  docker[39386]: requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://api.github.com/repos/linux-system-roles/network/statuses/225ba70a43473de3fd874bc62982cabb28cbfe35
```

**Comment by yontalcar** [comment]
Is it really a rate-limiting error? I'll add a line to the handler to print the message from the response though.
